begin;

create or replace function public.catalog_export_ref(p_prefix text, p_id uuid)
returns text language sql immutable strict set search_path = '' as $$
  select p_prefix || '_' || replace(p_id::text, '-', '_')
$$;

create or replace function public.export_catalog(p_venue_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_venue public.venues%rowtype; v_tenant public.tenants%rowtype; v_catalog jsonb;
begin
  select * into v_venue from public.venues where id=p_venue_id;
  if not found then raise exception 'VENUE_NOT_FOUND'; end if;
  if auth.role() <> 'service_role' and not public.user_is_tenant_admin(v_venue.tenant_id) then raise exception 'CATALOG_EXPORT_FORBIDDEN'; end if;
  select * into v_tenant from public.tenants where id=v_venue.tenant_id;
  v_catalog := jsonb_build_object(
    'categories', coalesce((select jsonb_agg(jsonb_build_object('ref',public.catalog_export_ref('category',c.id),'name',c.name,'icon',c.icon,'sortOrder',c.sort_order,'isActive',c.is_active,'unused',c.unused,'trace','{}'::jsonb,'source','{}'::jsonb) order by c.sort_order,c.name,c.id) from public.categories c where c.venue_id=p_venue_id),'[]'::jsonb),
    'saleFormats','[]'::jsonb,
    'tabs', coalesce((select jsonb_agg(jsonb_build_object('ref',public.catalog_export_ref('tab',t.id),'key',t.key,'label',t.label,'icon',t.icon,'sortOrder',t.sort_order,'isActive',t.is_active,'trace','{}'::jsonb) order by t.sort_order,t.label,t.id) from public.catalog_tabs t where t.venue_id=p_venue_id),'[]'::jsonb),
    'tabCategories', coalesce((select jsonb_agg(jsonb_build_object('ref',public.catalog_export_ref('tab_category',x.id),'tabRef',public.catalog_export_ref('tab',x.tab_id),'categoryRef',public.catalog_export_ref('category',x.category_id),'sortOrder',x.sort_order,'isActive',x.is_active,'source','{}'::jsonb) order by x.sort_order,x.id) from public.catalog_tab_categories x where x.venue_id=p_venue_id),'[]'::jsonb),
    'products', coalesce((select jsonb_agg(jsonb_build_object('ref',public.catalog_export_ref('product',p.id),'type',p.product_type,'name',p.name,'description',p.description,'imageRef',case when pi.id is null then null else public.catalog_export_ref('image',pi.id) end,'taxRate',p.tax_rate,'sortOrder',p.sort_order,'isActive',p.is_active,'trace','{}'::jsonb,'source','{}'::jsonb) order by p.sort_order,p.name,p.id) from public.products p left join public.product_images pi on pi.product_id=p.id where p.venue_id=p_venue_id),'[]'::jsonb),
    'variants', coalesce((select jsonb_agg(jsonb_build_object('ref',public.catalog_export_ref('variant',v.id),'productRef',public.catalog_export_ref('product',v.product_id),'name',v.name,'priceCents',v.price_cents,'sku',v.sku,'isDefault',v.is_default,'sortOrder',v.sort_order,'isActive',v.is_active,'trace','{}'::jsonb,'source','{}'::jsonb) order by v.product_id,v.sort_order,v.name,v.id) from public.product_variants v where v.venue_id=p_venue_id),'[]'::jsonb),
    'placements', coalesce((select jsonb_agg(jsonb_build_object('ref',public.catalog_export_ref('placement',x.id),'productRef',public.catalog_export_ref('product',x.product_id),'tabRef',public.catalog_export_ref('tab',x.tab_id),'categoryRef',case when x.category_id is null then null else public.catalog_export_ref('category',x.category_id) end,'variantRef',case when x.variant_id is null then null else public.catalog_export_ref('variant',x.variant_id) end,'featured',x.is_featured,'sortOrder',x.sort_order,'isActive',x.is_active,'trace','{}'::jsonb) order by x.tab_id,x.category_id nulls first,x.sort_order,x.id) from public.catalog_placements x where x.venue_id=p_venue_id and x.variant_id is not null or x.venue_id=p_venue_id and x.default_variant_id is null),'[]'::jsonb),
    'selectionGroups', coalesce((select jsonb_agg(jsonb_build_object('ref',public.catalog_export_ref('selection_group',g.id),'name',g.name,'type',g.kind,'sortOrder',g.sort_order,'isActive',g.is_active,'trace','{}'::jsonb,'source','{}'::jsonb) order by g.sort_order,g.name,g.id) from public.selection_groups g where g.venue_id=p_venue_id),'[]'::jsonb),
    'selectionGroupOptions', coalesce((select jsonb_agg(jsonb_build_object('ref',public.catalog_export_ref('selection_option',o.id),'groupRef',public.catalog_export_ref('selection_group',o.group_id),'productRef',public.catalog_export_ref('product',o.product_id),'variantRef',case when o.variant_id is null then null else public.catalog_export_ref('variant',o.variant_id) end,'supplementCents',o.supplement_cents,'defaultQuantity',o.default_quantity,'maxQuantity',o.max_quantity,'sortOrder',o.sort_order,'isActive',o.is_active,'trace','{}'::jsonb) order by o.group_id,o.sort_order,o.id) from public.selection_group_options o where o.venue_id=p_venue_id),'[]'::jsonb),
    'selectionAssignments', coalesce((select jsonb_agg(jsonb_build_object('ref',public.catalog_export_ref('selection_assignment',a.id),'productRef',public.catalog_export_ref('product',a.product_id),'groupRef',public.catalog_export_ref('selection_group',a.group_id),'variantRefs',coalesce((select jsonb_agg(public.catalog_export_ref('variant',av.variant_id) order by av.variant_id) from public.product_selection_group_assignment_variants av where av.assignment_id=a.id),'[]'::jsonb),'minSelection',a.min_selection,'maxSelection',a.max_selection,'sortOrder',a.sort_order,'isActive',a.is_active,'displayName',a.display_name,'trace','{}'::jsonb) order by a.product_id,a.sort_order,a.id) from public.product_selection_group_assignments a where a.venue_id=p_venue_id),'[]'::jsonb),
    'modifierGroups', coalesce((select jsonb_agg(jsonb_build_object('ref',public.catalog_export_ref('modifier_group',g.id),'name',g.name,'sortOrder',g.sort_order,'isActive',g.is_active,'trace','{}'::jsonb,'source','{}'::jsonb) order by g.sort_order,g.name,g.id) from public.modifier_groups g where g.venue_id=p_venue_id),'[]'::jsonb),
    'modifiers', coalesce((select jsonb_agg(jsonb_build_object('ref',public.catalog_export_ref('modifier',m.id),'groupRef',public.catalog_export_ref('modifier_group',m.group_id),'name',m.name,'supplementCents',m.supplement_cents,'isDefault',m.is_default,'sortOrder',m.sort_order,'isActive',m.is_active,'trace','{}'::jsonb) order by m.group_id,m.sort_order,m.id) from public.modifiers m where m.venue_id=p_venue_id),'[]'::jsonb),
    'modifierAssignments', coalesce((select jsonb_agg(jsonb_build_object('ref',public.catalog_export_ref('modifier_assignment',a.id),'productRef',public.catalog_export_ref('product',a.product_id),'groupRef',public.catalog_export_ref('modifier_group',a.group_id),'variantRefs',coalesce((select jsonb_agg(public.catalog_export_ref('variant',av.variant_id) order by av.variant_id) from public.product_modifier_group_assignment_variants av where av.assignment_id=a.id),'[]'::jsonb),'minSelection',a.min_selection,'maxSelection',a.max_selection,'sortOrder',a.sort_order,'isActive',a.is_active,'displayName',a.display_name,'trace','{}'::jsonb) order by a.product_id,a.sort_order,a.id) from public.product_modifier_group_assignments a where a.venue_id=p_venue_id),'[]'::jsonb),
    'images', coalesce((select jsonb_agg(jsonb_build_object('ref',public.catalog_export_ref('image',i.id),'productRef',public.catalog_export_ref('product',i.product_id),'file','images/'||public.catalog_export_ref('image',i.id)||case i.mime_type when 'image/jpeg' then '.jpg' when 'image/png' then '.png' when 'image/gif' then '.gif' when 'image/avif' then '.avif' else '.webp' end,'mimeType',i.mime_type,'sizeBytes',i.size_bytes,'sha256',i.sha256,'missing',false,'trace','{}'::jsonb,'source',jsonb_build_object('storagePath',i.storage_path)) order by i.product_id,i.id) from public.product_images i where i.venue_id=p_venue_id),'[]'::jsonb)
  );
  return jsonb_build_object('format','club-pos-catalog-export','schemaVersion',2,'metadata',jsonb_build_object('exportedAt',to_char(clock_timestamp() at time zone 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'origin',jsonb_build_object('tenant',jsonb_build_object('name',v_tenant.name),'venue',jsonb_build_object('name',v_venue.name)),'fiscal',jsonb_build_object('defaultTaxRate',v_venue.default_tax_rate,'currencyCode',v_venue.currency_code,'timezone',v_venue.timezone),'counts',(select jsonb_object_agg(key,jsonb_array_length(value)) from jsonb_each(v_catalog))),'catalog',v_catalog);
end; $$;

revoke all on function public.catalog_export_ref(text,uuid) from public, anon, authenticated;
revoke all on function public.export_catalog(uuid) from public, anon, authenticated;
grant execute on function public.export_catalog(uuid) to service_role;

commit;
