export * from '../features/crm/access/services/accessService'
export * from '../features/crm/plan/services/planService'
export * from '../features/crm/catalog/services/catalogAdminService'
export * from '../features/crm/catalog/services/catalogTransferService'
export * from '../features/crm/sales/services/salesReportsService'
export * from '../features/crm/analytics/services/analyticsService'
export * from '../features/crm/discounts/services/discountService'
