import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { hasTenantAddon, hasTenantCapability, hasTenantVenueCapability, normalizeTenantFeatures, updateTenantAddons } from '../src/features/platform/tenantFeatureAccess.ts'

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('tenant addons normalize legacy assignments and resolve commercial capabilities', () => {
  assert.deepEqual(normalizeTenantFeatures(['inventory_recipes', 'inventory', 'supplier_documents', 'supplier_document_scanning', 'discounts']), ['inventory', 'costing', 'purchases', 'document_ai', 'promotions'])
  assert.equal(hasTenantAddon({ features: [] }, 'promotions'), false)
  assert.equal(hasTenantCapability({ features: [] }, 'analytics_basic'), true)
  assert.equal(hasTenantCapability({ features: ['analytics_advanced', 'inventory', 'costing'] }, 'profitability'), true)
  assert.equal(hasTenantCapability({ features: ['document_ai', 'purchases', 'inventory'] }, 'document_ai'), true)
  assert.equal(hasTenantCapability({ features: ['reservations'] }, 'reservations'), false)
  assert.deepEqual(updateTenantAddons([], 'document_ai', true), ['inventory', 'purchases', 'document_ai'])
  assert.deepEqual(updateTenantAddons(['restaurant', 'reservations', 'production'], 'restaurant', false), [])
  assert.equal(hasTenantVenueCapability({ features: ['restaurant'], venue: { addonActivations: { restaurant: false }, inventoryEnabled: true, tablesEnabled: true, productionEnabled: false } }, 'restaurant'), false)
  assert.equal(hasTenantVenueCapability({ features: ['restaurant'], venue: { addonActivations: { restaurant: true }, inventoryEnabled: true, tablesEnabled: true, productionEnabled: false } }, 'restaurant'), true)
})

test('commercial addon migration keeps legacy clients and assignments usable', () => {
  const migration = read('../supabase/migrations/20260921120400_reframe_commercial_addons.sql')
  assert.doesNotMatch(migration, /set is_active = false, enabled_by_default = false/i)
  assert.match(migration, /when 'discounts' then 'promotions'/)
  assert.match(migration, /when 'inventory_recipes' then 'costing'/)
  assert.match(migration, /when 'supplier_documents' then 'purchases'/)
  assert.match(migration, /when 'supplier_document_scanning' then 'document_ai'/)
  assert.match(migration, /had_multi_device/)
  assert.match(migration, /legacy_request boolean := not \('__addon_catalog_v2' = any/)
  assert.match(read('../supabase/functions/manage-pos-users/index.ts'), /body\.featureCatalogVersion === 2 \? \[\.\.\.enabledFeatures, '__addon_catalog_v2'\]/)
  assert.match(read('../src/services/platformService.ts'), /featureCatalogVersion: 2/)
})

test('tenant sessions load feature assignments from the database', () => {
  const service = read('../src/services/posService.ts')
  const migration = read('../supabase/migrations/20260811230000_expose_tenant_features.sql')
  assert.match(service, /rpc\('get_current_tenant_features'/)
  assert.match(service, /features,/)
  assert.match(migration, /membership\.user_id = auth\.uid\(\)/)
  assert.match(migration, /tenant_feature_assignments/)
  assert.match(migration, /feature\.is_active = true/)
})

test('CRM and POS hide or disable every optional feature surface', () => {
  const appShell = read('../src/app/AppShell.tsx')
  const posPage = read('../src/app/PosPage.tsx')
  const crmPermissions = read('../src/features/crm/routing/crmPermissions.ts')
  const crmSidebar = read('../src/features/crm/layout/CrmSidebar.tsx')
  const formats = read('../src/features/crm/catalog/pages/CatalogFormatsPage.tsx')
  const tenantState = read('../src/features/session/services/loadTenantState.ts')
  const restaurantController = read('../src/features/restaurant/hooks/useRestaurantController.ts')
  const reservationsController = read('../src/features/reservations/hooks/useReservationsController.ts')
  const kds = read('../src/features/production/components/KdsPage.tsx')
  const productInventory = read('../src/features/crm/inventory/components/ProductInventoryEditor.tsx')

  assert.match(appShell, /hasTenantCapability\(context, 'restaurant'\)/)
  assert.match(appShell, /hasTenantCapability\(context, 'reservations'\)/)
  assert.match(appShell, /setInterval\(\(\) => void refreshFeatures\(\), 60_000\)/)
  assert.match(appShell, /addEventListener\('focus', handleFocus\)/)
  assert.match(posPage, /allowDiscount=\{props\.manualDiscountEnabled \|\| promotionsEnabled\}/)
  assert.match(posPage, /quickSale\.discountModalOpen/)
  assert.match(posPage, /reservationsEnabled && props\.reservations\.isOpen/)
  assert.match(posPage, /restaurantEnabled && restaurant\.pendingPayment/)
  assert.match(posPage, /hasTenantCapability\(props\.context, 'costing'\)/)
  assert.match(posPage, /loadInventoryPreparations\(props\.context\.venueId\)/)
  assert.match(posPage, /const hasPreparations = preparations\.length > 0/)
  assert.match(posPage, /setHasInventoryPreparations\(hasPreparations\)/)
  assert.match(posPage, /canOpenPreparations=\{inventoryRecipesEnabled && hasInventoryPreparations\}/)
  assert.match(posPage, /inventoryRecipesEnabled && hasInventoryPreparations && preparationsOpen/)
  assert.match(tenantState, /discounts: hasTenantAddon\(context, 'promotions'\) \? posCatalog\.discounts : \[\]/)
  assert.match(restaurantController, /if \(options\.enabled\) return[\s\S]*setPosView\(\{ type: 'quick_sale' \}\)/)
  assert.match(reservationsController, /if \(options\.enabled\) return[\s\S]*setIsOpen\(false\)/)
  assert.doesNotMatch(crmPermissions, /multi_device/)
  assert.match(crmPermissions, /tables: 'restaurant'/)
  assert.match(crmPermissions, /'inventory-stock': 'inventory'/)
  assert.match(crmPermissions, /'inventory-preparations': 'costing'/)
  assert.match(crmSidebar, /allowedInventoryItems\.length/)
  assert.match(formats, /inventoryFeatureEnabled \? <div/)
  assert.match(kds, /inventoryRecipesEnabled \? <Button/)
  assert.match(productInventory, /inventoryRecipesEnabled \|\| value !== 'recipe'/)
})
