import { useShallow } from 'zustand/react/shallow'
import { usePrintAgentStore } from '../store/usePrintAgentStore'

export function usePrintAgent() {
  return usePrintAgentStore(useShallow((state) => ({
    isConnected: state.connectionStatus === 'connected',
    connectionStatus: state.connectionStatus,
    serverInfo: state.serverInfo,
    printers: state.printers,
    selectedPrinter: state.selectedPrinter,
    selectedPrinterId: state.selectedPrinterId,
    isDiscovering: state.isDiscoveringPrinters,
    discoveryProgress: state.discoveryProgress,
    currentJob: state.currentJob,
    jobs: state.jobs,
    preferences: state.preferences,
    lastError: state.lastConnectionError,
    lastConnectionCheckAt: state.lastConnectionCheckAt,
    lastSuccessfulConnectionAt: state.lastSuccessfulConnectionAt,
    lastResponseTimeMs: state.lastResponseTimeMs,
    lastPrintAt: state.lastPrintAt,
    isCheckingConnection: state.isCheckingConnection,
    isLoadingServerInfo: state.isLoadingServerInfo,
    isLoadingPrinters: state.isLoadingPrinters,
    isSelectingPrinter: state.isSelectingPrinter,
    isTestingPrinter: state.isTestingPrinter,
    isPrintingTicket: state.isPrintingTicket,
    isOpeningCashDrawer: state.isOpeningCashDrawer,
    isLoadingJobs: state.isLoadingJobs,
    baseUrl: state.baseUrl,
    hasToken: Boolean(state.token),
    checkConnection: state.checkConnection,
    loadServerInfo: state.loadServerInfo,
    loadPrinters: state.loadPrinters,
    discoverPrinters: state.discoverPrinters,
    selectPrinter: state.selectPrinter,
    testPrinter: state.testPrinter,
    printTicket: state.printTicket,
    openCashDrawer: state.openCashDrawer,
    loadJobs: state.loadJobs,
    setBaseUrl: state.setBaseUrl,
    setToken: state.setToken,
    updatePreferences: state.updatePreferences,
    clearError: state.clearError,
    resetConfiguration: state.resetConfiguration,
    getDiagnosticReport: state.getDiagnosticReport,
  })))
}

