import {
  Apple,
  Beef,
  Beer,
  CakeSlice,
  Candy,
  ChefHat,
  Citrus,
  Clock,
  Coffee,
  Cookie,
  Croissant,
  CupSoda,
  Dessert,
  Donut,
  Drumstick,
  EggFried,
  Fish,
  Flame,
  Gamepad2,
  GlassWater,
  Grape,
  Ham,
  Heart,
  IceCreamBowl,
  IceCreamCone,
  Martini,
  Milk,
  Moon,
  Music,
  Package,
  Pizza,
  Popcorn,
  ReceiptText,
  Salad,
  Sandwich,
  ShoppingBasket,
  Soup,
  Sparkles,
  Star,
  Store,
  Sun,
  Tag,
  Utensils,
  Vegan,
  Wheat,
  Wine,
  WineOff,
  type LucideIcon,
} from 'lucide-react'

export type CatalogIconOption = {
  Icon: LucideIcon
  key: string
  label: string
}

export const catalogIconOptions: CatalogIconOption[] = [
  { key: 'receipt', label: 'General', Icon: ReceiptText },
  { key: 'beer_bottle', label: 'Cerveza', Icon: Beer },
  { key: 'cocktail', label: 'Cóctel', Icon: Martini },
  { key: 'copa', label: 'Copa', Icon: Wine },
  { key: 'cubata', label: 'Cubata', Icon: Martini },
  { key: 'shot', label: 'Chupito', Icon: Wine },
  { key: 'soft_bottle', label: 'Refresco', Icon: GlassWater },
  { key: 'utensils', label: 'Restaurante', Icon: Utensils },
  { key: 'chef_hat', label: 'Cocina', Icon: ChefHat },
  { key: 'coffee', label: 'Café', Icon: Coffee },
  { key: 'cup_soda', label: 'Bebida', Icon: CupSoda },
  { key: 'milk', label: 'Leche', Icon: Milk },
  { key: 'wine_off', label: 'Sin alcohol', Icon: WineOff },
  { key: 'pizza', label: 'Pizza', Icon: Pizza },
  { key: 'sandwich', label: 'Bocadillo', Icon: Sandwich },
  { key: 'salad', label: 'Ensalada', Icon: Salad },
  { key: 'soup', label: 'Sopa', Icon: Soup },
  { key: 'beef', label: 'Carne', Icon: Beef },
  { key: 'ham', label: 'Jamón', Icon: Ham },
  { key: 'drumstick', label: 'Pollo', Icon: Drumstick },
  { key: 'fish', label: 'Pescado', Icon: Fish },
  { key: 'vegan', label: 'Vegano', Icon: Vegan },
  { key: 'egg', label: 'Huevos', Icon: EggFried },
  { key: 'apple', label: 'Fruta', Icon: Apple },
  { key: 'citrus', label: 'Cítricos', Icon: Citrus },
  { key: 'grape', label: 'Uvas', Icon: Grape },
  { key: 'wheat', label: 'Pan', Icon: Wheat },
  { key: 'cake', label: 'Tarta', Icon: CakeSlice },
  { key: 'dessert', label: 'Postres', Icon: Dessert },
  { key: 'ice_cream', label: 'Helado', Icon: IceCreamBowl },
  { key: 'ice_cream_cone', label: 'Cono', Icon: IceCreamCone },
  { key: 'cookie', label: 'Galleta', Icon: Cookie },
  { key: 'donut', label: 'Dónut', Icon: Donut },
  { key: 'croissant', label: 'Bollería', Icon: Croissant },
  { key: 'candy', label: 'Dulces', Icon: Candy },
  { key: 'popcorn', label: 'Snacks', Icon: Popcorn },
  { key: 'store', label: 'Tienda', Icon: Store },
  { key: 'basket', label: 'Cesta', Icon: ShoppingBasket },
  { key: 'package', label: 'Paquete', Icon: Package },
  { key: 'star', label: 'Destacados', Icon: Star },
  { key: 'heart', label: 'Favoritos', Icon: Heart },
  { key: 'flame', label: 'Caliente', Icon: Flame },
  { key: 'sparkles', label: 'Especiales', Icon: Sparkles },
  { key: 'tag', label: 'Ofertas', Icon: Tag },
  { key: 'clock', label: 'Horario', Icon: Clock },
  { key: 'music', label: 'Música', Icon: Music },
  { key: 'gamepad', label: 'Juegos', Icon: Gamepad2 },
  { key: 'sun', label: 'Día', Icon: Sun },
  { key: 'moon', label: 'Noche', Icon: Moon },
]

const catalogIcons = new Map(catalogIconOptions.map((option) => [option.key, option.Icon]))

export function getCatalogIconComponent(icon: string | null | undefined, fallback: LucideIcon = ReceiptText) {
  return catalogIcons.get(icon ?? '') ?? fallback
}
