import { ArrowLeft, ArrowRight, Check, Eye, EyeOff, ExternalLink, LoaderCircle, X } from 'lucide-react'
import { useState } from 'react'
import { Button } from '../../../components/ui'
import { getPrintAgentErrorMessage } from '../api/PrintAgentError'
import { usePrintAgent } from '../hooks/usePrintAgent'
import { PrinterList } from './PrinterList'

export function PrintAgentSetupWizard({ canOpenDrawer, onClose }: { canOpenDrawer: boolean; onClose: () => void }) {
  const agent = usePrintAgent()
  const [step, setStep] = useState(1)
  const [url, setUrl] = useState(agent.baseUrl)
  const [token, setToken] = useState('')
  const [showToken, setShowToken] = useState(false)
  const [message, setMessage] = useState<string | null>(null)

  async function run(action: () => Promise<unknown>, success: string, next?: number) {
    setMessage(null)
    try { await action(); setMessage(success); if (next) setStep(next) }
    catch (error) { setMessage(getPrintAgentErrorMessage(error)) }
  }

  const busy = agent.isCheckingConnection || agent.isLoadingServerInfo || agent.isDiscovering || agent.isSelectingPrinter || agent.isTestingPrinter || agent.isOpeningCashDrawer
  return <div className="fixed inset-0 z-[65] bg-[var(--background)] text-[var(--foreground)] sm:flex sm:items-center sm:justify-center sm:bg-black/60 sm:p-4">
    <section aria-labelledby="print-wizard-title" aria-modal="true" className="flex h-[100svh] w-full flex-col bg-[var(--surface)] sm:h-auto sm:max-h-[92svh] sm:max-w-3xl sm:rounded-[var(--radius)] sm:border sm:border-[var(--separator)]" role="dialog">
      <header className="flex items-start justify-between gap-4 border-b border-[var(--separator)] p-5"><div><p className="text-xs font-black uppercase text-[var(--accent)]">Paso {step} de 9</p><h2 className="text-2xl font-black" id="print-wizard-title">Configuracion del servidor de impresion</h2></div><Button disabled={busy} onClick={onClose} size="sm"><X className="h-4 w-4" /></Button></header>
      <div className="h-1 bg-[var(--surface-secondary)]"><div className="h-full bg-[var(--accent)] transition-all" style={{ width: `${step / 9 * 100}%` }} /></div>
      <div className="min-h-0 flex-1 overflow-y-auto p-5">
        {step === 1 ? <div className="grid gap-4"><h3 className="text-xl font-black">Direccion del agente</h3><p className="text-sm text-[var(--muted)]">Usa el hostname local asignado al agente. No se escanea la red desde Safari.</p><label><span className="mb-2 block text-sm font-bold">URL HTTPS</span><input autoCapitalize="none" autoCorrect="off" className="min-h-14 w-full rounded-[var(--radius)] border border-[var(--field-border)] bg-[var(--field)] px-4 font-mono text-sm" onChange={(event) => setUrl(event.target.value)} spellCheck={false} value={url} /></label><Button disabled={busy} onClick={() => void run(async () => { const normalized = agent.setBaseUrl(url); setUrl(normalized); const ok = await agent.checkConnection(); if (!ok) throw agent.lastError || new Error('No accesible') }, 'Servidor conectado.', 3)} variant="primary">{agent.isCheckingConnection ? <LoaderCircle className="h-4 w-4 animate-spin" /> : null}Probar conexion</Button><Button onClick={() => { try { agent.setBaseUrl(url); setStep(2) } catch (error) { setMessage(getPrintAgentErrorMessage(error)) } }}>Continuar</Button></div> : null}
        {step === 2 ? <div className="grid gap-4"><h3 className="text-xl font-black">Certificado y acceso local</h3><p className="text-sm leading-6 text-[var(--muted)]">Si la conexion falla, abre el agente en Safari. Instala el certificado raiz y activa la confianza completa en Ajustes &gt; General &gt; Informacion &gt; Ajustes de confianza de certificados. Comprueba tambien Wi-Fi, mDNS, firewall, aislamiento de clientes y CORS.</p><a className="inline-flex min-h-14 items-center justify-center gap-2 rounded-[var(--radius)] bg-[var(--accent)] px-4 font-bold text-[var(--accent-foreground)]" href={`${agent.baseUrl}/health`} rel="noreferrer" target="_blank"><ExternalLink className="h-5 w-5" />Abrir agente en una nueva pestana</a><Button disabled={busy} onClick={() => void run(async () => { if (!await agent.checkConnection()) throw new Error('No se ha podido conectar. Revisa la ayuda anterior.') }, 'Servidor conectado.', 3)}>Volver a probar</Button></div> : null}
        {step === 3 ? <div className="grid gap-4"><h3 className="text-xl font-black">Token del agente</h3><p className="text-sm text-[var(--muted)]">Se guardara solo en este dispositivo. No se envia a Supabase ni aparece en diagnosticos.</p><label><span className="mb-2 block text-sm font-bold">Token Bearer</span><span className="flex rounded-[var(--radius)] border border-[var(--field-border)] bg-[var(--field)]"><input autoCapitalize="none" autoComplete="off" className="min-h-14 min-w-0 flex-1 bg-transparent px-4 font-mono outline-none" onChange={(event) => setToken(event.target.value)} type={showToken ? 'text' : 'password'} value={token} /><button aria-label={showToken ? 'Ocultar token' : 'Mostrar token'} className="min-h-14 min-w-14" onClick={() => setShowToken((value) => !value)} type="button">{showToken ? <EyeOff className="mx-auto h-5 w-5" /> : <Eye className="mx-auto h-5 w-5" />}</button></span></label><Button disabled={!token.trim()} onClick={() => { agent.setToken(token); setToken(''); setStep(4) }} variant="primary">Guardar token</Button></div> : null}
        {step === 4 ? <div className="grid gap-4"><h3 className="text-xl font-black">Comprobar autenticacion</h3><p className="text-sm text-[var(--muted)]">Se consultara la informacion protegida del agente.</p><Button disabled={busy} onClick={() => void run(() => agent.loadServerInfo(), 'Autenticacion correcta.', 5)} variant="primary">{agent.isLoadingServerInfo ? <LoaderCircle className="h-4 w-4 animate-spin" /> : null}Comprobar autenticacion</Button></div> : null}
        {step === 5 ? <div className="grid gap-4"><h3 className="text-xl font-black">Descubrir impresoras</h3><p className="text-sm text-[var(--muted)]">El agente buscara impresoras termicas en la red local.</p>{agent.discoveryProgress ? <p className="font-mono text-sm">Escaneadas: {agent.discoveryProgress.scanned ?? '-'} / {agent.discoveryProgress.total ?? '-'} · Encontradas: {agent.discoveryProgress.found ?? agent.printers.length}</p> : null}<Button disabled={busy} onClick={() => void run(() => agent.discoverPrinters(), 'Descubrimiento completado.', 6)} variant="primary">{agent.isDiscovering ? <LoaderCircle className="h-4 w-4 animate-spin" /> : null}Descubrir impresoras</Button></div> : null}
        {step === 6 ? <div className="grid gap-4"><h3 className="text-xl font-black">Seleccionar impresora</h3><p className="text-sm text-[var(--muted)]">Si hay varias, elige explicitamente la que corresponde a esta terminal.</p><PrinterList disabled={busy} onSelect={(id) => void run(() => agent.selectPrinter(id), 'Impresora seleccionada.')} onTest={(id) => void run(() => agent.testPrinter(id), 'Ticket de prueba enviado.')} printers={agent.printers} selectedPrinterId={agent.selectedPrinterId} /><Button disabled={!agent.selectedPrinterId} onClick={() => setStep(7)} variant="primary">Continuar</Button></div> : null}
        {step === 7 ? <div className="grid gap-4"><h3 className="text-xl font-black">Impresion de prueba</h3><p className="text-sm text-[var(--muted)]">Comprueba papel, corte y conectividad antes de continuar.</p><Button disabled={busy} onClick={() => void run(() => agent.testPrinter(), 'Ticket de prueba enviado.', 8)} variant="primary">{agent.isTestingPrinter ? <LoaderCircle className="h-4 w-4 animate-spin" /> : null}Imprimir ticket de prueba</Button></div> : null}
        {step === 8 ? <div className="grid gap-4"><h3 className="text-xl font-black">Apertura del cajon</h3><p className="text-sm text-[var(--muted)]">Esta accion fisica requiere permiso y confirmacion.</p><Button disabled={busy || !canOpenDrawer} onClick={() => { if (window.confirm('¿Quieres abrir el cajon para realizar la prueba?')) void run(() => agent.openCashDrawer(), 'Cajon abierto.', 9) }} variant="primary">{agent.isOpeningCashDrawer ? <LoaderCircle className="h-4 w-4 animate-spin" /> : null}Probar apertura del cajon</Button>{!canOpenDrawer ? <p className="text-sm font-semibold text-amber-700">Tu usuario no tiene permiso para abrir el cajon. Puedes omitir esta prueba.</p> : null}<Button onClick={() => setStep(9)}>Omitir</Button></div> : null}
        {step === 9 ? <div className="grid place-items-center gap-4 py-8 text-center"><span className="grid h-16 w-16 place-items-center rounded-full bg-emerald-500/15 text-emerald-600"><Check className="h-8 w-8" /></span><h3 className="text-2xl font-black">Configuracion completada</h3><p className="max-w-md text-sm text-[var(--muted)]">La configuracion queda vinculada a este local y terminal. El token permanece en el almacenamiento local del dispositivo.</p><Button onClick={onClose} variant="primary">Finalizar</Button></div> : null}
        {message ? <div className="mt-5 rounded-[var(--radius)] border border-[var(--separator)] bg-[var(--surface-secondary)] p-3 text-sm font-bold">{message}</div> : null}
      </div>
      <footer className="flex justify-between border-t border-[var(--separator)] p-4"><Button disabled={step === 1 || busy} onClick={() => setStep((value) => Math.max(1, value - 1))}><ArrowLeft className="h-4 w-4" />Anterior</Button>{step < 9 ? <Button disabled={busy} onClick={() => setStep((value) => Math.min(9, value + 1))}>Siguiente<ArrowRight className="h-4 w-4" /></Button> : null}</footer>
    </section>
  </div>
}

